/* Print pack — pre-rendered into #print-root, dirty-checked before printing.
   Structure: branded cover → Group summary page → one page per asset
   (summary, curated tiles, a compact workforce & talent row, two charts,
   watch list) → data quality → methodology appendix. A4 portrait: every
   section must fit one sheet, so page numbers count sheets
   (tests/outlook-print-export.spec.mjs checks it with page.pdf()); break
   rules live in print.css.
   Persona-scoped: only the persona's in-scope units (Access.printScopes) and
   visible pages print; restricted tiles print restricted. */

const PrintPack = (() => {

  let dirty = true;
  const ASSET_TILE_KEYS = [
    'headcount_close', 'attr_annualised', 'tt_count', 'succession_coverage',
    'learning_coverage_all', 'idp_coverage', 'posting_compliance', 'female_pct',
    'ltifr', 'contract_compliance_idx', 'contract_hc', 'near_retirement_pct'
  ];
  // key tiles of the Phase 8 areas: Overview demographics and budget, positions,
  // joining, movement, TA, absence, performance cycle
  const TALENT_TILE_KEYS = [
    'demo_hc_yoy_pct', 'bva_variance_pct', 'pb_vacancy_pct', 'join_hires_ytd',
    'mv_promotion_rate', 'ta_ttf_median', 'absenteeism_pct', 'midyear_review_pct'
  ];

  // One pending build at a time. The idle callback carries a deadline: a
  // renderer that never reports an idle period (a busy page, some headless
  // builds) still gets its pack within a second instead of never.
  let queued = false;
  let lastError = null;
  function markDirty() {
    dirty = true;
    if (queued) return;
    queued = true;
    const run = () => { queued = false; ensureFresh(); };
    if (window.requestIdleCallback) window.requestIdleCallback(run, { timeout: 1000 });
    else setTimeout(run, 400);
  }

  function ensureFresh() {
    if (!dirty) return;
    if (App.state.mode === 'gate') { document.getElementById('print-root').innerHTML = ''; dirty = false; return; }
    try {
      build();
      dirty = false;
      lastError = null;
    } catch (e) {
      // stays dirty, so the next change or beforeprint retries the build
      lastError = String((e && e.stack) || e);
      throw e;
    }
  }

  // compute with a temporary asset scope (band reset to All for print pages)
  function withScope(asset, fn) {
    const saved = { ...App.state.filters };
    App.state.filters = { ...saved, asset, band: 'All' };
    try { return fn(); } finally { App.state.filters = saved; }
  }

  function footer(n, m) {
    return `<div class="pp-footer">
      <span class="wordmark"><span class="wm-mark">AM/NS</span>
        <span class="wm-sub">ArcelorMittal Nippon Steel India</span></span>
      <span><strong>Smarter Steels. Brighter Futures.</strong></span>
      <span>As of ${esc(CONFIG.asOf)} · ${esc(periodText(Compute.ctxNow()))}</span>
      <span class="chip ${App.state.mode === 'mock' ? 'chip-mock' : 'chip-live'}">${App.state.mode === 'mock' ? 'Illustrative data' : esc(App.state.loadedFileNames.join(', ') || 'Loaded data')}</span>
      <span class="chip">Business: ${esc(Compute.ctxNow().segment)}</span>
      <span class="chip">Persona: ${esc(Access.label())}</span>
      <span>${esc(App.confidentialText())}</span>
      <span class="pp-page">Page ${n} of ${m}</span>
    </div>`;
  }

  function coverPage() {
    return `<section class="print-page pp-cover">
      <div>
        <div class="wordmark"><span class="wm-mark" style="font-size:20pt">AM/NS</span>
          <span class="wm-sub">ArcelorMittal Nippon Steel India</span></div>
        <div class="cover-stroke"></div>
        <h1>HR Dashboard <span style="color:var(--red)">@AM/NS</span></h1>
        <p class="cover-sub">${Access.isDefault() ? 'CHRO' : 'Persona'} print pack · ${esc(periodText(Compute.ctxNow()))} · as of ${esc(CONFIG.asOf)}</p>
        <p class="cover-sub">${esc(Access.printScopes().join(' · '))} · Business: ${esc(Compute.ctxNow().segment)}</p>
        <p class="cover-sub">Prepared for persona: ${esc(Access.label())} (mockup persona view — not a security control)</p>
        <p class="cover-sub" style="margin-top:14pt">${App.state.mode === 'mock'
          ? 'ILLUSTRATIVE DATA — every figure in this pack is synthetic, generated by a seeded PRNG.'
          : 'Computed locally in the browser from: ' + esc(App.state.loadedFileNames.join(', '))}</p>
      </div>
      __FOOTER__
    </section>`;
  }

  function summaryBlock(asset) {
    const s = ExecSummary.forAsset(asset);
    return `<div class="exec-band" style="margin-bottom:8pt">
      <p class="exec-verdict">${esc(s.verdict)}</p>
      <ul class="exec-points">${s.points.map((p) =>
        `<li class="${p.type === 'watch' ? 'is-watch' : p.type === 'good' ? 'is-good' : ''}">${esc(p.text)}</li>`).join('')}
      </ul></div>`;
  }

  function watchList(asset) {
    const rows = [];
    for (const f of Scorecard.compute().functions) {
      for (const r of f.rows) {
        if (r.score != null && r.score < 90) {
          rows.push([r.entry.label, r.current == null ? '—' : fmtNum(r.current, r.entry.decimals), r.target == null ? '—' : fmtNum(r.target, r.entry.decimals), fmtNum(r.score, 1)]);
        }
      }
    }
    if (!rows.length) return '<p class="chart-note">No scorecard metric is off target for this scope.</p>';
    return `<div class="section-head"><h2>Watch list — off-target metrics</h2></div>` +
      UI.tableHTML(['Metric', 'Actual', 'Target', 'Score'], rows.slice(0, 8));
  }

  function tilesBlock(keys, cls = '') {
    return `<div class="tile-grid pp-tiles ${cls}">${keys.map((k) => UI.tileHTML(k)).join('')}</div>`;
  }

  const scopes = () => Access.chartScopes();

  function assetCharts(asset) {
    const m = Compute.build(), ctx = Compute.ctxNow();
    const attr = Charts.card({
      title: 'Annualised attrition — monthly', infoKey: 'attr_annualised',
      body: (m.has('exits') && m.has('employee_master'))
        ? Charts.line({
            months: ChartData.monthsAxis(ctx),
            series: [
              { label: asset, role: 'focus', values: ChartData.monthsAxis(ctx).map((mi) => Compute.monthAttritionRate(m, ChartData.subCtx(ctx, asset), mi)) },
              ...(scopes().includes('Group') ? [{ label: 'Group', role: 'group', values: ChartData.monthsAxis(ctx).map((mi) => Compute.monthAttritionRate(m, { ...ctx, asset: 'Group' }, mi)) }] : [])
            ],
            yFmt: (v) => fmtPct(v, 0), h: 140
          })
        : '<div class="chart-empty">exits.csv not loaded</div>'
    });
    const hc = Charts.card({
      title: 'Permanent headcount — month-end', infoKey: 'headcount_close',
      body: m.has('employee_master')
        ? Charts.line({
            months: ChartData.monthsAxis(ctx),
            series: [{ label: asset, role: 'focus', values: ChartData.monthsAxis(ctx).map((mi) => Compute.activesAt(m, ChartData.subCtx(ctx, asset), 'Permanent', monthEndDay(mi)).length) }],
            yFmt: (v) => fmtInt(v), h: 140
          })
        : '<div class="chart-empty">employee_master.csv not loaded</div>'
    });
    return `<div class="card-grid pp-charts">${attr}${hc}</div>`;
  }

  function unitPage(asset) {
    return withScope(asset, () => `<section class="print-page pp-unit">
      <div class="section-head"><h2 style="font-size:14pt">${esc(asset)} — ${asset === 'Group' ? 'Group executive summary' : 'Asset HR head summary'}</h2>
        <span class="sub">${esc(periodText(Compute.ctxNow()))}${Compute.ctxNow().segment !== 'All' ? ' · Business: ' + esc(Compute.ctxNow().segment) : ''}${Compute.ctxNow().fn !== 'All' ? ' · Line function: ' + esc(Compute.ctxNow().fn) : ''}</span></div>
      ${summaryBlock(asset)}
      ${tilesBlock(ASSET_TILE_KEYS)}
      <div class="section-head pp-subhead"><h2>Workforce &amp; talent</h2><span class="sub">headcount, budget, positions, hiring, movement, absence, performance cycle</span></div>
      ${tilesBlock(TALENT_TILE_KEYS, 'pp-tiles-compact')}
      ${asset === 'Group' ? '' : assetCharts(asset)}
      ${watchList(asset)}
      __FOOTER__
    </section>`);
  }

  function qualityPage() {
    const q = DataQuality.compute();
    return `<section class="print-page">
      <div class="section-head"><h2 style="font-size:14pt">Data quality</h2>
        <span class="sub">transparent score — the method is printed with it${Access.persona().scope !== 'all' ? ' · dataset-wide, not narrowed to ' + esc(Access.label())
          : Compute.ctxNow().segment !== 'All' ? ' · dataset-wide, not narrowed to Business: ' + esc(Compute.ctxNow().segment) : ''}</span></div>
      <div class="tile-grid pp-tiles">
        <div class="tile"><span class="tile-label">Overall</span>
          <span class="tile-value">${q.overall == null ? '—' : fmtNum(q.overall, 1) + '%'}</span></div>
        ${Object.entries(q.dims).map(([k, v]) => `<div class="tile"><span class="tile-label">${esc(k)}</span>
          <span class="tile-value">${v == null ? '—' : fmtNum(v, 1) + '%'}</span>
          <span class="tile-meta">${esc(q.method[k])}</span></div>`).join('')}
      </div>
      <div class="section-head"><h2>Issues</h2></div>
      ${q.issues.length ? UI.tableHTML(['Severity', 'Where', 'What'], q.issues.slice(0, 14).map((i) => [i.severity, i.where, i.what])) : '<p>No issues detected.</p>'}
      __FOOTER__
    </section>`;
  }

  // The appendix is longer than a sheet, so it is cut into sheet-sized sections,
  // each with its own footer, marking and page number. A row's height is
  // estimated from its text against the fixed column widths in print.css
  // (.pp-method: characters per line per column); budgets are in text lines.
  const METHOD_CHARS = [34, 74, 26];
  const METHOD_LINES = { first: 60, next: 66 };
  const methodLines = (row) => Math.max(...row.map((c, i) => Math.ceil(String(c).length / METHOD_CHARS[i]) || 1)) + 0.4;

  function methodologyPages() {
    const rows = REGISTRY.map((e) => [e.label, e.formulaText.replace(/\n/g, ' '), e.inputs.map((i) => i.dataset).join(', ')]);
    const chunks = [[]];
    let used = 0;
    for (const r of rows) {
      const n = methodLines(r);
      if (chunks[chunks.length - 1].length && used + n > (chunks.length === 1 ? METHOD_LINES.first : METHOD_LINES.next)) { chunks.push([]); used = 0; }
      chunks[chunks.length - 1].push(r);
      used += n;
    }
    return chunks.map((c, i) => `<section class="print-page pp-method-page">
      <div class="section-head"><h2 style="font-size:14pt">Methodology appendix${chunks.length > 1 ? ` (${i + 1} of ${chunks.length})` : ''}</h2>
        <span class="sub">generated from the formula registry — every metric in the pack is defined here</span></div>
      ${i === 0 ? `<p style="font-size:9pt; margin-bottom:6pt">Scoring: higher-is-better Score = Actual ÷ Target × 100;
      lower-is-better Score = (2 × Target − Actual) ÷ Target × 100. Function totals are means of scored
      metrics; “Target not set” is excluded. Albert Sans embedded under the SIL OFL 1.1.</p>` : ''}
      <div class="pp-method">${UI.tableHTML(['Metric', 'Formula', 'Inputs'], c)}</div>
      __FOOTER__
    </section>`);
  }

  function build() {
    const root = document.getElementById('print-root');
    const pages = [
      coverPage(),
      ...Access.printScopes().map((a) => unitPage(a)),
      ...(Access.canSeeTab('quality') ? [qualityPage()] : []),
      ...methodologyPages()
    ];
    const total = pages.length;
    root.innerHTML = pages.map((p, i) => p.replace('__FOOTER__', footer(i + 1, total))).join('');
    // the pack is paper, not UI: strip interactive attributes and controls so
    // the print DOM never collides with the live app (selectors, aria, focus)
    root.querySelectorAll('.i-btn, [data-drill-csv]').forEach((el) => el.remove());
    root.querySelectorAll('[data-key], [data-drill], [data-info], [data-jump], [data-setasset], [data-tip], [data-access], [role="button"]').forEach((el) => {
      for (const a of ['data-key', 'data-drill', 'data-info', 'data-jump', 'data-setasset', 'data-tip', 'data-access', 'role', 'tabindex', 'aria-label']) el.removeAttribute(a);
    });
  }

  window.addEventListener('beforeprint', ensureFresh);

  return { markDirty, ensureFresh, build, get lastError() { return lastError; } };
})();
