/* Print pack — pre-rendered into #print-root, dirty-checked before printing.
   Structure: branded cover → Group summary page → one page per asset
   (summary, curated tiles, two charts, watch list) → data quality →
   methodology appendix. A4 portrait; break rules live in print.css. */

const PrintPack = (() => {

  let dirty = true;
  const ASSET_TILE_KEYS = [
    'headcount_close', 'attr_annualised', 'tt_count', 'succession_coverage',
    'learning_coverage_all', 'idp_coverage', 'posting_compliance', 'female_pct',
    'ltifr', 'contract_compliance_idx', 'contract_hc', 'near_retirement_pct'
  ];

  function markDirty() {
    dirty = true;
    const idle = window.requestIdleCallback || ((fn) => setTimeout(fn, 400));
    idle(() => ensureFresh());
  }

  function ensureFresh() {
    if (!dirty) return;
    if (App.state.mode === 'gate') { document.getElementById('print-root').innerHTML = ''; dirty = false; return; }
    build();
    dirty = false;
  }

  // compute with a temporary asset scope (band reset to All for print pages)
  function withScope(asset, fn) {
    const saved = { ...App.state.filters };
    App.state.filters = { ...saved, asset, band: 'All' };
    try { return fn(); } finally { App.state.filters = saved; }
  }

  function footer(n, m) {
    return `<div class="pp-footer">
      <span class="wordmark"><span class="wm-mark">AM/NS</span>
        <span class="wm-sub">ArcelorMittal Nippon Steel India</span></span>
      <span><strong>Smarter Steels. Brighter Futures.</strong></span>
      <span>As of ${esc(CONFIG.asOf)} · ${esc(CONFIG.periodLabel)}</span>
      <span class="chip ${App.state.mode === 'mock' ? 'chip-mock' : 'chip-live'}">${App.state.mode === 'mock' ? 'Illustrative data' : esc(App.state.loadedFileNames.join(', ') || 'Loaded data')}</span>
      <span>Confidential — illustrative mockup, no real employee data</span>
      <span class="pp-page">Page ${n} of ${m}</span>
    </div>`;
  }

  function coverPage() {
    return `<section class="print-page pp-cover">
      <div>
        <div class="wordmark"><span class="wm-mark" style="font-size:20pt">AM/NS</span>
          <span class="wm-sub">ArcelorMittal Nippon Steel India</span></div>
        <div class="cover-stroke"></div>
        <h1>HR Dashboard <span style="color:var(--red)">@AM/NS</span></h1>
        <p class="cover-sub">CHRO print pack · ${esc(CONFIG.periodLabel)} · as of ${esc(CONFIG.asOf)}</p>
        <p class="cover-sub">Group + Hazira · Paradeep · Vizag · Kirandul</p>
        <p class="cover-sub" style="margin-top:14pt">${App.state.mode === 'mock'
          ? 'ILLUSTRATIVE DATA — every figure in this pack is synthetic, generated by a seeded PRNG.'
          : 'Computed locally in the browser from: ' + esc(App.state.loadedFileNames.join(', '))}</p>
      </div>
      __FOOTER__
    </section>`;
  }

  function summaryBlock(asset) {
    const s = ExecSummary.forAsset(asset);
    return `<div class="exec-band" style="margin-bottom:8pt">
      <p class="exec-verdict">${esc(s.verdict)}</p>
      <ul class="exec-points">${s.points.map((p) =>
        `<li class="${p.type === 'watch' ? 'is-watch' : p.type === 'good' ? 'is-good' : ''}">${esc(p.text)}</li>`).join('')}
      </ul></div>`;
  }

  function watchList(asset) {
    const rows = [];
    for (const f of Scorecard.compute().functions) {
      for (const r of f.rows) {
        if (r.score != null && r.score < 90) {
          rows.push([r.entry.label, r.current == null ? '—' : fmtNum(r.current, r.entry.decimals), r.target == null ? '—' : fmtNum(r.target, r.entry.decimals), fmtNum(r.score, 1)]);
        }
      }
    }
    if (!rows.length) return '<p class="chart-note">No scorecard metric is off target for this scope.</p>';
    return `<div class="section-head"><h2>Watch list — off-target metrics</h2></div>` +
      UI.tableHTML(['Metric', 'Actual', 'Target', 'Score'], rows.slice(0, 8));
  }

  function tilesBlock(keys) {
    return `<div class="tile-grid pp-tiles">${keys.map((k) => UI.tileHTML(k)).join('')}</div>`;
  }

  function assetCharts(asset) {
    const m = Compute.build(), ctx = Compute.ctxNow();
    const attr = Charts.card({
      title: 'Annualised attrition — monthly',
      body: (m.has('exits') && m.has('employee_master'))
        ? Charts.line({
            months: ChartData.monthsAxis(ctx),
            series: [
              { label: asset, role: 'focus', values: ChartData.monthsAxis(ctx).map((mi) => Compute.monthAttritionRate(m, ChartData.subCtx(ctx, asset), mi)) },
              { label: 'Group', role: 'group', values: ChartData.monthsAxis(ctx).map((mi) => Compute.monthAttritionRate(m, { ...ctx, asset: 'Group' }, mi)) }
            ],
            yFmt: (v) => fmtPct(v, 0), h: 180
          })
        : '<div class="chart-empty">exits.csv not loaded</div>'
    });
    const hc = Charts.card({
      title: 'Permanent headcount — month-end',
      body: m.has('employee_master')
        ? Charts.line({
            months: ChartData.monthsAxis(ctx),
            series: [{ label: asset, role: 'focus', values: ChartData.monthsAxis(ctx).map((mi) => Compute.activesAt(m, ChartData.subCtx(ctx, asset), 'Permanent', monthEndDay(mi)).length) }],
            yFmt: (v) => fmtInt(v), h: 180
          })
        : '<div class="chart-empty">employee_master.csv not loaded</div>'
    });
    return `<div class="card-grid pp-charts">${attr}${hc}</div>`;
  }

  function unitPage(asset) {
    return withScope(asset, () => `<section class="print-page">
      <div class="section-head"><h2 style="font-size:14pt">${esc(asset)} — ${asset === 'Group' ? 'Group executive summary' : 'Asset HR head summary'}</h2>
        <span class="sub">${esc(CONFIG.periodLabel)}</span></div>
      ${summaryBlock(asset)}
      ${tilesBlock(ASSET_TILE_KEYS)}
      ${asset === 'Group' ? '' : assetCharts(asset)}
      ${watchList(asset)}
      __FOOTER__
    </section>`);
  }

  function qualityPage() {
    const q = DataQuality.compute();
    return `<section class="print-page">
      <div class="section-head"><h2 style="font-size:14pt">Data quality</h2>
        <span class="sub">transparent score — the method is printed with it</span></div>
      <div class="tile-grid pp-tiles">
        <div class="tile"><span class="tile-label">Overall</span>
          <span class="tile-value">${q.overall == null ? '—' : fmtNum(q.overall, 1) + '%'}</span></div>
        ${Object.entries(q.dims).map(([k, v]) => `<div class="tile"><span class="tile-label">${esc(k)}</span>
          <span class="tile-value">${v == null ? '—' : fmtNum(v, 1) + '%'}</span>
          <span class="tile-meta">${esc(q.method[k])}</span></div>`).join('')}
      </div>
      <div class="section-head"><h2>Issues</h2></div>
      ${q.issues.length ? UI.tableHTML(['Severity', 'Where', 'What'], q.issues.slice(0, 14).map((i) => [i.severity, i.where, i.what])) : '<p>No issues detected.</p>'}
      __FOOTER__
    </section>`;
  }

  function methodologyPage() {
    const rows = REGISTRY.map((e) => [e.label, e.formulaText.replace(/\n/g, ' '), e.inputs.map((i) => i.dataset).join(', ')]);
    return `<section class="print-page">
      <div class="section-head"><h2 style="font-size:14pt">Methodology appendix</h2>
        <span class="sub">generated from the formula registry — every metric in the pack is defined here</span></div>
      <p style="font-size:9pt; margin-bottom:6pt">Scoring: higher-is-better Score = Actual ÷ Target × 100;
      lower-is-better Score = (2 × Target − Actual) ÷ Target × 100. Function totals are means of scored
      metrics; “Target not set” is excluded. Albert Sans embedded under the SIL OFL 1.1.</p>
      <div class="pp-method">${UI.tableHTML(['Metric', 'Formula', 'Inputs'], rows)}</div>
      __FOOTER__
    </section>`;
  }

  function build() {
    const root = document.getElementById('print-root');
    const pages = [
      coverPage(),
      unitPage('Group'),
      ...CONFIG.assets.map((a) => unitPage(a)),
      qualityPage(),
      methodologyPage()
    ];
    const total = pages.length;
    root.innerHTML = pages.map((p, i) => p.replace('__FOOTER__', footer(i + 1, total))).join('');
    // the pack is paper, not UI: strip interactive attributes and controls so
    // the print DOM never collides with the live app (selectors, aria, focus)
    root.querySelectorAll('.i-btn, [data-drill-csv]').forEach((el) => el.remove());
    root.querySelectorAll('[data-key], [data-drill], [data-info], [data-jump], [data-setasset], [data-tip], [role="button"]').forEach((el) => {
      for (const a of ['data-key', 'data-drill', 'data-info', 'data-jump', 'data-setasset', 'data-tip', 'role', 'tabindex', 'aria-label']) el.removeAttribute(a);
    });
  }

  window.addEventListener('beforeprint', ensureFresh);

  return { markDirty, ensureFresh, build };
})();
