/* Methodology tab — generated from the formula registry and schemas.
   No metric appears in the product that is not in this appendix. */

TabRenderers.methodology = (panel) => {
  const tabName = (id) => (TABS.find((t) => t.id === id) || { label: id }).label;
  const byTab = {};
  for (const e of REGISTRY) (byTab[e.tab] = byTab[e.tab] || []).push(e);

  const metricRows = (entries) => entries.map((e) => [
    e.label,
    e.key,
    `<span style="font-family:ui-monospace,Menlo,Consolas,monospace;font-size:11.5px;white-space:pre-wrap">${esc(e.formulaText)}</span>`,
    e.inputs.map((i) => i.dataset + '.csv').join(', '),
    e.direction ? (e.direction === 'higher' ? 'higher is better' : 'lower is better') : '—',
    e.scorecard || '—'
  ]);

  const sections = Object.entries(byTab).map(([tab, entries]) => `
    <div class="section-head"><h2>${esc(tabName(tab))}</h2><span class="sub">${entries.length} metrics</span></div>
    ${UI.tableHTML(['Metric', 'Registry key', 'Formula', 'Inputs', 'Direction', 'Scorecard function'], metricRows(entries))}
  `).join('');

  panel.innerHTML = `
    <div class="exec-band">
      <p class="exec-verdict">Methodology &amp; definitions</p>
      <ul class="exec-points">
        <li>One <strong>formula registry</strong> is the single source of truth: it generates every tile,
          every “i” popover, the upload templates, the data dictionary, the scorecard rows and this appendix.
          No metric appears anywhere that is not on this page.</li>
        <li><strong>Scoring model</strong> — higher-is-better: <em>Score = Actual ÷ Target × 100</em>;
          lower-is-better: <em>Score = (2 × Target − Actual) ÷ Target × 100</em>. Function total = mean of scored
          metrics; cumulative score = mean of function totals; “Target not set” is excluded, never assumed.</li>
        <li><strong>Periods</strong> — the period selector is illustrative (${esc(CONFIG.periodLabel)}); the as-of date
          (${esc(CONFIG.asOf)}) and retirement age (${CONFIG.retirementAge}) are single configurable constants.</li>
        <li><strong>Productivity, Cost &amp; Safety</strong> is a steel-specific block added for AM/NS —
          it extends the classic HR MIS structure that the other tabs follow.</li>
        <li><strong>Grievance tracking</strong> is out of scope: no input template carries grievance data,
          and this dashboard shows nothing it cannot compute from its declared inputs.</li>
        <li><strong>Privacy</strong> — all computation happens in this browser tab. The page makes zero network
          requests, stores nothing (no cookies, no local storage), and all exports are local downloads.
          In illustrative mode every number is synthetic, generated by a seeded PRNG.</li>
        <li><strong>Targets</strong> come only from targets.csv (or the illustrative demo targets in mock mode).
          No external benchmarks are invented.</li>
        <li><strong>Type</strong> — Albert Sans, embedded under the SIL Open Font License 1.1
          (see OFL-AlbertSans.txt in the repository). PNG chart exports fall back to the system font stack.</li>
      </ul>
    </div>
    ${sections}
    <div class="section-head"><h2>Input templates</h2><span class="sub">the full column dictionary is downloadable as data_dictionary.csv</span></div>
    ${UI.tableHTML(['Template', 'Contents', 'Source system'],
      SCHEMA_IDS.map((id) => [id + '.csv', SCHEMAS[id].desc, SCHEMAS[id].source || '—']))}`;
};
